backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Ayarları"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "content/site.json"
        fields:
          - { label: "Üst Yazı", name: "eyebrow", widget: "string" }
          - { label: "Ana Başlık", name: "hero_title", widget: "string" }
          - { label: "Ana Açıklama", name: "hero_text", widget: "text" }

  - name: "events"
    label: "Etkinlikler"
    files:
      - label: "Etkinlik Listesi"
        name: "events_file"
        file: "content/events.json"
        fields:
          - label: "Etkinlikler"
            name: "events"
            widget: "list"
            fields:
              - { label: "Başlık", name: "title", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "Fotoğraf", name: "image", widget: "image", required: false }
